version: '3.7'

services:
  hexo:
    container_name: hexo-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/blog'
      - '/blog/node_modules'
    ports:
      - '4000:4000'
