version: '3.7'

volumes:
    astro:

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./astro:/blog
      - ./astro/node_modules:/blog/node_modules
    ports:
      - '4321:4321'
