version: '3.7'

services:
  hexo:
    build:
      context: .
      network: host
    volumes:
      - type: bind
        source: ./hexo
        target: /blog
        read_only: false
      - /blog/node_modules
    ports:
      - '4000:4000'
