## This set of configs WILL BE read from yours site's _config.yml if available,
# otherwise the default values will be used

#  Header menu items
menu:
  Home: /
  Blog: /blog
  Category: /categories

rss: /atom.xml

excerpt_link: Read More
fancybox: true

sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# widget behavior
archive_type: 'monthly'
show_count: false

favicon: images/favicon
twitter:
google_plus:
fb_admins:
fb_app_id:
google_analytics: UA-46261454-1



# ### The next set of settings are Theme related an will NOT be read from your site's _config
# you still can change the values here if you wish.
