layout:
  blog: Blog
  category: Category
  tag: Tag
  prev_text: « Prev
  next_text: Next »
  comments: Comments
  page_n: Page %d

  article:
    published: Published
    updated: Updated
    share: Share
